# Generated by Django 6.1 on 2026-08-12 09:54

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("lexicon", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TastingSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        unique=True,
                        verbose_name="uuid",
                    ),
                ),
                (
                    "wine_type",
                    models.CharField(
                        choices=[
                            ("still_white", "Still white"),
                            ("still_red", "Still red"),
                            ("rose", "Rosé"),
                            ("sparkling", "Sparkling"),
                            ("fortified", "Fortified"),
                        ],
                        max_length=16,
                        verbose_name="wine type",
                    ),
                ),
                (
                    "wine_name",
                    models.CharField(blank=True, max_length=200, verbose_name="wine"),
                ),
                (
                    "producer",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="producer"
                    ),
                ),
                (
                    "region",
                    models.CharField(blank=True, max_length=200, verbose_name="region"),
                ),
                (
                    "vintage",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="vintage"
                    ),
                ),
                (
                    "tasted_blind",
                    models.BooleanField(
                        default=False,
                        help_text="Whether the taster knew what was in the glass.",
                        verbose_name="tasted blind",
                    ),
                ),
                (
                    "actual_grape",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="actual grape"
                    ),
                ),
                (
                    "actual_origin",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="actual origin"
                    ),
                ),
                (
                    "quality",
                    models.CharField(blank=True, max_length=32, verbose_name="quality"),
                ),
                (
                    "guessed_grape",
                    models.CharField(
                        blank=True, max_length=64, verbose_name="guessed grape"
                    ),
                ),
                (
                    "colour_hex",
                    models.CharField(
                        blank=True,
                        help_text="Swatch of the recorded colour, for the journal list.",
                        max_length=7,
                        verbose_name="colour",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("in_progress", "In progress"),
                            ("completed", "Completed"),
                            ("abandoned", "Abandoned"),
                        ],
                        default="in_progress",
                        max_length=16,
                        verbose_name="status",
                    ),
                ),
                ("started_at", models.DateTimeField(verbose_name="started at")),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="completed at"
                    ),
                ),
                (
                    "client_updated_at",
                    models.DateTimeField(verbose_name="client updated at"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "lexicon",
                    models.ForeignKey(
                        help_text="The vocabulary version this was tasted against.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sessions",
                        to="lexicon.lexicon",
                        verbose_name="lexicon",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tasting_sessions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="taster",
                    ),
                ),
            ],
            options={
                "verbose_name": "tasting session",
                "verbose_name_plural": "tasting sessions",
                "ordering": ("-started_at",),
            },
        ),
        migrations.CreateModel(
            name="PhaseResponse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "phase",
                    models.CharField(
                        choices=[
                            ("look", "Look"),
                            ("smell", "Smell"),
                            ("taste", "Taste"),
                            ("conclude", "Conclude"),
                        ],
                        max_length=16,
                        verbose_name="phase",
                    ),
                ),
                (
                    "question_code",
                    models.SlugField(max_length=64, verbose_name="question"),
                ),
                (
                    "values",
                    models.JSONField(blank=True, default=list, verbose_name="values"),
                ),
                (
                    "skipped",
                    models.BooleanField(
                        default=False,
                        help_text="The taster was genuinely unsure and moved on.",
                        verbose_name="skipped",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="responses",
                        to="tastings.tastingsession",
                        verbose_name="session",
                    ),
                ),
            ],
            options={
                "verbose_name": "phase response",
                "verbose_name_plural": "phase responses",
                "ordering": ("session", "id"),
            },
        ),
        migrations.AddIndex(
            model_name="tastingsession",
            index=models.Index(
                fields=["user", "-started_at"], name="tastings_ta_user_id_568301_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="tastingsession",
            index=models.Index(
                fields=["user", "status"], name="tastings_ta_user_id_d15d96_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="phaseresponse",
            constraint=models.UniqueConstraint(
                fields=("session", "question_code"), name="response_unique_per_question"
            ),
        ),
    ]
