# Generated by Django 6.1 on 2026-08-12 09:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Lexicon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "version",
                    models.CharField(
                        help_text="Identifier for this vocabulary set, e.g. 2026.1.",
                        max_length=32,
                        unique=True,
                        verbose_name="version",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="What changed in this version, and why.",
                        verbose_name="notes",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=False,
                        help_text="The version new sessions are started against. Only one.",
                        verbose_name="active",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
            ],
            options={
                "verbose_name": "lexicon",
                "verbose_name_plural": "lexicons",
                "ordering": ("-created_at",),
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("is_active", True)),
                        fields=("is_active",),
                        name="lexicon_only_one_active",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "phase",
                    models.CharField(
                        choices=[
                            ("look", "Look"),
                            ("smell", "Smell"),
                            ("taste", "Taste"),
                            ("conclude", "Conclude"),
                        ],
                        max_length=16,
                        verbose_name="phase",
                    ),
                ),
                (
                    "code",
                    models.SlugField(
                        help_text="Stable identifier stored on every response, e.g. acidity.",
                        max_length=64,
                        verbose_name="code",
                    ),
                ),
                (
                    "prompt",
                    models.CharField(
                        help_text="Readable in under three seconds, at the table.",
                        max_length=120,
                        verbose_name="prompt",
                    ),
                ),
                (
                    "help_text",
                    models.TextField(
                        blank=True,
                        help_text="The optional 'why this matters' note. A hint, not a lesson.",
                        verbose_name="help text",
                    ),
                ),
                (
                    "control",
                    models.CharField(
                        choices=[
                            ("single", "Pick one"),
                            ("multi", "Pick any"),
                            ("scale", "Scale, low to high"),
                        ],
                        default="single",
                        max_length=16,
                        verbose_name="control",
                    ),
                ),
                (
                    "wine_types",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Styles this applies to. Empty means all of them.",
                        verbose_name="wine types",
                    ),
                ),
                (
                    "order",
                    models.PositiveSmallIntegerField(default=0, verbose_name="order"),
                ),
                (
                    "lexicon",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questions",
                        to="lexicon.lexicon",
                        verbose_name="lexicon",
                    ),
                ),
            ],
            options={
                "verbose_name": "question",
                "verbose_name_plural": "questions",
                "ordering": ("phase", "order", "id"),
            },
        ),
        migrations.CreateModel(
            name="Option",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.SlugField(max_length=64, verbose_name="code")),
                ("label", models.CharField(max_length=80, verbose_name="label")),
                (
                    "swatch",
                    models.CharField(
                        blank=True,
                        help_text="Hex colour for appearance options. Always shown beside the label, never instead of it — the colour is decoration, the word is the answer.",
                        max_length=7,
                        verbose_name="swatch",
                    ),
                ),
                (
                    "wine_types",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Styles this applies to. Empty means all of them.",
                        verbose_name="wine types",
                    ),
                ),
                (
                    "order",
                    models.PositiveSmallIntegerField(default=0, verbose_name="order"),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        help_text="The category this descriptor sits under, if any.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="lexicon.option",
                        verbose_name="parent",
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="options",
                        to="lexicon.question",
                        verbose_name="question",
                    ),
                ),
            ],
            options={
                "verbose_name": "option",
                "verbose_name_plural": "options",
                "ordering": ("question", "order", "id"),
            },
        ),
        migrations.AddConstraint(
            model_name="question",
            constraint=models.UniqueConstraint(
                fields=("lexicon", "code"), name="question_code_unique_per_lexicon"
            ),
        ),
        migrations.AddConstraint(
            model_name="option",
            constraint=models.UniqueConstraint(
                fields=("question", "code"), name="option_code_unique_per_question"
            ),
        ),
    ]
