# Generated by Django 6.1 on 2026-08-12 13:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lexicon", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="question",
            name="help_text",
        ),
        migrations.AddField(
            model_name="option",
            name="guidance",
            field=models.CharField(
                blank=True,
                help_text="How to know it is this one and not the one next to it. The difference between medium and high acidity is the whole difficulty; the label alone does not teach it.",
                max_length=160,
                verbose_name="guidance",
            ),
        ),
        migrations.AddField(
            model_name="option",
            name="implies",
            field=models.SlugField(
                blank=True,
                help_text="Code of an Inference this descriptor is evidence for, e.g. malolactic. Empty when it implies nothing in particular.",
                max_length=64,
                verbose_name="implies",
            ),
        ),
        migrations.AddField(
            model_name="option",
            name="origin",
            field=models.CharField(
                blank=True,
                choices=[
                    ("primary", "From the grape"),
                    ("secondary", "From the winemaking"),
                    ("tertiary", "From age"),
                ],
                help_text="For aroma and flavour descriptors: where this came from. The app sorts by it so the taster does not have to.",
                max_length=16,
                verbose_name="origin",
            ),
        ),
        migrations.AddField(
            model_name="question",
            name="how_to_tell",
            field=models.TextField(
                blank=True,
                help_text="The physical instruction: what to do with the glass or your mouth, and what sensation to look for. Shown on the question itself, not hidden behind a toggle — this is the part that teaches.",
                verbose_name="how to tell",
            ),
        ),
        migrations.AddField(
            model_name="question",
            name="short_label",
            field=models.CharField(
                blank=True,
                help_text="One or two words for the navigation rail, e.g. Acidity.",
                max_length=32,
                verbose_name="short label",
            ),
        ),
        migrations.AddField(
            model_name="question",
            name="why_it_matters",
            field=models.TextField(
                blank=True,
                help_text="What the answer tells you about the wine. Available on tap.",
                verbose_name="why it matters",
            ),
        ),
        migrations.CreateModel(
            name="Inference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.SlugField(
                        help_text="Matches Option.implies, e.g. malolactic.",
                        max_length=64,
                        verbose_name="code",
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        help_text="The name of the thing, e.g. Malolactic conversion.",
                        max_length=80,
                        verbose_name="label",
                    ),
                ),
                (
                    "explanation",
                    models.TextField(
                        help_text="What it is and why those descriptors point at it, in plain words. Two sentences at most — this is read at a table, not a desk.",
                        verbose_name="explanation",
                    ),
                ),
                (
                    "order",
                    models.PositiveSmallIntegerField(default=0, verbose_name="order"),
                ),
                (
                    "lexicon",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inferences",
                        to="lexicon.lexicon",
                        verbose_name="lexicon",
                    ),
                ),
            ],
            options={
                "verbose_name": "inference",
                "verbose_name_plural": "inferences",
                "ordering": ("order", "id"),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("lexicon", "code"),
                        name="inference_code_unique_per_lexicon",
                    )
                ],
            },
        ),
    ]
