# Generated by Django 6.1 on 2026-08-13 11:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lexicon", "0002_remove_question_help_text_option_guidance_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="axis",
            field=models.CharField(
                blank=True,
                choices=[
                    ("carry", "Distance the sensation travels"),
                    ("burst", "How much arrives at once"),
                    ("fill", "Quantity on the tongue"),
                    ("spread", "How far across the mouth it reaches"),
                    ("rise", "Warmth climbing from the throat"),
                    ("weight", "Thickness — how heavy it feels"),
                    ("grain", "Friction — grip and texture"),
                    ("length", "Time it lasts after swallowing"),
                    ("swatch", "Hue and depth — the one coloured mark"),
                ],
                help_text="What this question measures, which decides the mark its options carry. Leave blank for a question that takes no mark — anything categorical, and everything in Conclude.",
                max_length=16,
                verbose_name="axis",
            ),
        ),
    ]
