"""
apps/tastings/models.py — The tasting record.

Two models, where PRD §9 sketches three. The sketch has a separate
``Conclusion`` alongside ``PhaseResponse``, but the conclude phase asks
lexicon questions like every other phase — quality, readiness, the grape
guess and the confidence rating are all `Question` rows. Giving them a second
home would store the same answers in two shapes and hand us two places for
them to disagree. So:

    TastingSession   identity, the wine, lifecycle, and the small set of
                     denormalised columns the journal filters on.
    PhaseResponse    every answer, including the conclude phase.

What the sketch's ``Conclusion`` uniquely carried — the *actual* wine, revealed
after a blind tasting so the guess can be scored — lives on the session as the
``actual_*`` fields, because it is a property of the bottle rather than an
answer to a prompt.

Sync model: the client owns the session while it is being tasted. It generates
the uuid, holds state locally, and pushes the whole session up on pause and on
completion. ``client_updated_at`` is the clock that matters — the server takes
the newer of what it holds and what arrives, so a phone that was offline
through three phases does not lose them to a stale write from another tab.
"""

from __future__ import annotations

import uuid as uuid_lib

from django.conf import settings
from django.contrib.auth.base_user import AbstractBaseUser
from django.db import models
from django.urls import reverse
from django.utils.translation import gettext_lazy as _

from apps.core.enums import Phase, SessionStatus, WineType


class TastingSessionQuerySet(models.QuerySet["TastingSession"]):
    """Queryset helpers for `TastingSession`."""

    def for_user(self, user: AbstractBaseUser) -> TastingSessionQuerySet:
        """Scope to one taster's sessions.

        Every journal and API view goes through this. Tasting notes are
        personal (PRD §8), and a filter that has to be remembered at each call
        site is one that will eventually be forgotten.

        Args:
            user: The signed-in user.

        Returns:
            That user's sessions.

        """
        return self.filter(user=user)

    def completed(self) -> TastingSessionQuerySet:
        """Scope to sessions that reached the end of the sequence."""
        return self.filter(status=SessionStatus.COMPLETED)


class TastingSession(models.Model):
    """One wine, one sitting, one run through the sequence."""

    #: Generated by the client before the first tap, so a session started with
    #: no connectivity already has its final identity and syncs later without
    #: renumbering. This is the key the upsert endpoint is idempotent on.
    uuid = models.UUIDField(
        _("uuid"), default=uuid_lib.uuid4, unique=True, editable=False
    )
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        related_name="tasting_sessions",
        verbose_name=_("taster"),
    )
    lexicon = models.ForeignKey(
        "lexicon.Lexicon",
        on_delete=models.PROTECT,
        related_name="sessions",
        verbose_name=_("lexicon"),
        help_text=_("The vocabulary version this was tasted against."),
    )
    wine_type = models.CharField(
        _("wine type"), max_length=16, choices=WineType.choices
    )

    # ——— The wine —————————————————————————————————————————————
    # All optional. A blind tasting is named afterwards, if at all, and
    # forcing a name up front would break the practice the app exists for
    # (PRD §6.1).
    wine_name = models.CharField(_("wine"), max_length=200, blank=True)
    producer = models.CharField(_("producer"), max_length=200, blank=True)
    region = models.CharField(_("region"), max_length=200, blank=True)
    vintage = models.PositiveSmallIntegerField(_("vintage"), null=True, blank=True)
    tasted_blind = models.BooleanField(
        _("tasted blind"),
        default=False,
        help_text=_("Whether the taster knew what was in the glass."),
    )

    # ——— The reveal ———————————————————————————————————————————
    # Filled in after the fact, when a blind taster checks the label. Kept
    # apart from the guess (a `PhaseResponse`) so the journal can show one
    # against the other.
    actual_grape = models.CharField(_("actual grape"), max_length=120, blank=True)
    actual_origin = models.CharField(_("actual origin"), max_length=120, blank=True)

    # ——— Denormalised for the journal —————————————————————————
    # Copies of three answers, written by `sync_denormalised_fields`. The
    # journal filters and sorts on these (PRD §6.2), and the alternative is a
    # JSON containment lookup on `PhaseResponse.values`, which SQLite does not
    # support — so the filter would work in production and fail in the tests.
    # These are a cache: `PhaseResponse` remains the source of truth.
    quality = models.CharField(_("quality"), max_length=32, blank=True)
    guessed_grape = models.CharField(_("guessed grape"), max_length=64, blank=True)
    colour_hex = models.CharField(
        _("colour"),
        max_length=7,
        blank=True,
        help_text=_("Swatch of the recorded colour, for the journal list."),
    )

    status = models.CharField(
        _("status"),
        max_length=16,
        choices=SessionStatus.choices,
        default=SessionStatus.IN_PROGRESS,
    )
    started_at = models.DateTimeField(_("started at"))
    completed_at = models.DateTimeField(_("completed at"), null=True, blank=True)
    #: The client's own clock at its last local change. Last write wins on it.
    client_updated_at = models.DateTimeField(_("client updated at"))
    created_at = models.DateTimeField(_("created at"), auto_now_add=True)
    updated_at = models.DateTimeField(_("updated at"), auto_now=True)

    objects = TastingSessionQuerySet.as_manager()

    class Meta:
        verbose_name = _("tasting session")
        verbose_name_plural = _("tasting sessions")
        ordering = ("-started_at",)
        indexes = [
            models.Index(fields=["user", "-started_at"]),
            models.Index(fields=["user", "status"]),
        ]

    def __str__(self) -> str:
        """Return the wine and date, or the style when tasted blind."""
        return f"{self.display_name} — {self.started_at:%Y-%m-%d}"

    def get_absolute_url(self) -> str:
        """Return this session's journal entry."""
        return reverse("journal:detail", kwargs={"uuid": self.uuid})

    @property
    def display_name(self) -> str:
        """Return the best name available for this session.

        A blind tasting that was never revealed has no name at all, so fall
        back to the style — "Still red, 4 March" beats an empty row.
        """
        parts = [p for p in (self.producer, self.wine_name) if p]
        if parts:
            return " ".join(parts)
        return str(WineType(self.wine_type).label)

    @property
    def is_complete(self) -> bool:
        """Return whether the session reached the Conclude phase."""
        return self.status == SessionStatus.COMPLETED

    def answers(self) -> dict[str, list[str]]:
        """Return every answer as ``{question_code: values}``.

        Skipped questions are omitted: "unsure" is a legitimate outcome
        (PRD §6.1) and should read as absence, not as an empty answer.

        Returns:
            The answered questions and their selected option codes.

        """
        return {
            response.question_code: response.values
            for response in self.responses.all()
            if not response.skipped
        }

    def sync_denormalised_fields(self) -> None:
        """Refresh the journal's filter columns from the stored responses.

        Called by the sync endpoint after responses are written. Deliberately
        not a `save()` override: the fields are derived from *other rows*, so
        recomputing them on every save would be both wasteful and, for a save
        that happens before the responses land, wrong.
        """
        from apps.lexicon.models import Option

        answers = self.answers()
        self.quality = next(iter(answers.get("quality", [])), "")
        self.guessed_grape = next(iter(answers.get("guess_grape", [])), "")

        colour = next(iter(answers.get("colour", [])), "")
        swatch = ""
        if colour:
            swatch = (
                Option.objects.filter(
                    question__lexicon=self.lexicon,
                    question__code="colour",
                    code=colour,
                )
                .values_list("swatch", flat=True)
                .first()
                or ""
            )
        self.colour_hex = swatch
        self.save(update_fields=["quality", "guessed_grape", "colour_hex"])


class PhaseResponse(models.Model):
    """One question's answer within a session."""

    session = models.ForeignKey(
        TastingSession,
        on_delete=models.CASCADE,
        related_name="responses",
        verbose_name=_("session"),
    )
    phase = models.CharField(_("phase"), max_length=16, choices=Phase.choices)
    question_code = models.SlugField(_("question"), max_length=64)
    #: Always a list, even for a single-select question. One shape means the
    #: client, the API and the journal never branch on the control type when
    #: reading an answer back.
    values = models.JSONField(_("values"), default=list, blank=True)
    skipped = models.BooleanField(
        _("skipped"),
        default=False,
        help_text=_("The taster was genuinely unsure and moved on."),
    )

    class Meta:
        verbose_name = _("phase response")
        verbose_name_plural = _("phase responses")
        ordering = ("session", "id")
        constraints = [
            models.UniqueConstraint(
                fields=["session", "question_code"],
                name="response_unique_per_question",
            ),
        ]

    def __str__(self) -> str:
        """Return the question code and what was selected."""
        if self.skipped:
            return f"{self.question_code}: skipped"
        return f"{self.question_code}: {', '.join(self.values)}"
